error on action_required

diff --git a/.github/workflows/comment_coverage_report.yml b/.github/workflows/comment_coverage_report.yml
--- a/.github/workflows/comment_coverage_report.yml
+++ b/.github/workflows/comment_coverage_report.yml
@@ -33,7 +33,8 @@ jobs:
       - name: Conclusion Analysis
         if: steps.wait-for-coverage.outputs.run-conclusion == 'action_required'
         run: |
-          echo "::warning::Code coverage workflow requires manual approval. After approval, please re-run this workflow to post the coverage report."
+          echo "::error::First-time contributor workflows require manual approval. After approval, please re-run the comment coverage workflows to post the coverage report."
+          exit 1
 
   comment_coverage_report:
     name: Comment Code Coverage Report
@@ -41,12 +42,9 @@ jobs:
     permissions:
       pull-requests: write
 
-    # The expression if: ${{ !cancelled() && needs.check_code_coverage_completed.outputs.conclusion != 'action_required' }}
-    # ensures that this job only runs if the previous job was not cancelled and does not require manual approval.
-    # This check prevents running the job unnecessarily when a manual approval is needed.
-    if: |
-      !cancelled() &&
-      needs.check_code_coverage_completed.outputs.conclusion != 'action_required'
+    # The expression if: ${{ !cancelled() }} runs a job or step regardless of its success or failure while responding to cancellations,
+    # serving as a cancellation-compliant alternative to if: ${{ always() }} in concurrent workflows.
+    if: ${{ !cancelled() }}
     runs-on: ubuntu-latest
     steps:
       - name: Find CI workflow run for PR
