Improve variable name handling for device name key.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -216,11 +216,15 @@ jobs:
         run: |
           AVD_NAME=$(echo "${{ matrix.device_profile }}" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_')
           DEVICE_NAME_KEY=$(echo $AVD_NAME | tr '[:lower:]' '[:upper:]')
+          echo "Using $DEVICE_NAME_KEY to look up device information"
+          if [[ -z ${!$DEVICE_NAME_KEY+x} ]]; then echo "Using unknown AVD name: ${{ matrix.device_profile }}"; exit 1; fi
+
           DENSITY_VARIABLE_NAME="${DEVICE_NAME_KEY}[0]"
           WIDTH_PX_VARIABLE_NAME="${DEVICE_NAME_KEY}[1]"
           HEIGHT_PX_VARIABLE_NAME="${DEVICE_NAME_KEY}[2]"
           # For reference: https://unix.stackexchange.com/a/364097 & https://unix.stackexchange.com/a/560315.
-          if [[ -z ${!DENSITY_VARIABLE_NAME+x} || -z ${!WIDTH_PX_VARIABLE_NAME+x} || -z ${!HEIGHT_PX_VARIABLE_NAME+x} ]]; then echo "Using unknown AVD name: ${{ matrix.device_profile }}"; exit 1; fi
+          if [[ -z ${!DENSITY_VARIABLE_NAME+x} || -z ${!WIDTH_PX_VARIABLE_NAME+x} || -z ${!HEIGHT_PX_VARIABLE_NAME+x} ]]; then echo "Using invalid AVD name: ${{ matrix.device_profile }}"; exit 1; fi
+
           echo "::set-env name=AVD_NAME::$AVD_NAME"
           echo "::set-env name=AVD_DENSITY::${!DENSITY_VARIABLE_NAME}"
           echo "::set-env name=AVD_WIDTH_PX::${!WIDTH_PX_VARIABLE_NAME}"
