Update main.yml
Add parsing code for AVD device settings.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -189,12 +189,6 @@ jobs:
         with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-jars-{{ checksum "build.gradle" }}
-      - name: Debug
-        run: |
-          echo "Pixel XL -- $PIXEL_XL"
-          echo "Pixel XL elem 0 -- ${PIXEL_XL[0]}"
-          echo "Pixel XL elem 1 -- ${PIXEL_XL[1]}"
-          echo "Pixel XL elem 2 -- ${PIXEL_XL[2]}"
 
       # Set up Java 8 since it's required for building binaries dependent on the Android SDK.
       - name: Set up JDK 1.8
@@ -223,20 +217,20 @@ jobs:
           AVD_NAME=$(echo "${{ matrix.device_profile }}" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '_')
           DEVICE_NAME_KEY=$(echo $AVD_NAME | tr '[:lower:]' '[:upper:]')
           echo "Using $DEVICE_NAME_KEY to look up device information"
-          if [[ -z ${!DEVICE_NAME_KEY+x} ]]; then echo "Using unknown AVD name: ${{ matrix.device_profile }}"; exit 1; fi
-          
-          DENSITY_VARIABLE_NAME="${DEVICE_NAME_KEY}[0]"
-          WIDTH_PX_VARIABLE_NAME="${DEVICE_NAME_KEY}[1]"
-          HEIGHT_PX_VARIABLE_NAME="${DEVICE_NAME_KEY}[2]"
           # For reference: https://unix.stackexchange.com/a/364097 & https://unix.stackexchange.com/a/560315.
-          if [[ -z ${!DENSITY_VARIABLE_NAME+x} ]]; then echo "Using invalid AVD name: ${{ matrix.device_profile }}. No density defined."; exit 1; fi
-          if [[ -z ${!WIDTH_PX_VARIABLE_NAME+x} ]]; then echo "Using invalid AVD name: ${{ matrix.device_profile }}. No width defined."; exit 1; fi
-          if [[ -z ${!HEIGHT_PX_VARIABLE_NAME+x} ]]; then echo "Using invalid AVD name: ${{ matrix.device_profile }}. No height defined."; exit 1; fi
+          if [[ -z ${!DEVICE_NAME_KEY+x} ]]; then echo "Using unknown AVD name: ${{ matrix.device_profile }}"; exit 1; fi
+
+          # Reference: https://stackoverflow.com/a/10586169 & https://unix.stackexchange.com/a/193042.
+          # Note that this additional parsing is necessary since GitHub stores environment variables
+          # as strings, so arrays can't be explicitly defined.
+          DEVICE_SETTINGS_FLATTENED="${!DEVICE_NAME_KEY}
+          delim=',' read -r -a DEVICE_SETTINGS <<< "$DEVICE_SETTINGS_FLATTENED"
+          if [[ ${#DEVICE_SETTINGS[@]} != 3 ]]; then echo "Using invalid AVD name: ${{ matrix.device_profile }}. Expected 3 device specs, not: ${#DEVICE_SETTINGS[@]}"; exit 1; fi
 
           echo "::set-env name=AVD_NAME::$AVD_NAME"
-          echo "::set-env name=AVD_DENSITY::${!DENSITY_VARIABLE_NAME}"
-          echo "::set-env name=AVD_WIDTH_PX::${!WIDTH_PX_VARIABLE_NAME}"
-          echo "::set-env name=AVD_HEIGHT_PX::${!HEIGHT_PX_VARIABLE_NAME}"
+          echo "::set-env name=AVD_DENSITY::${DENSITY_VARIABLE_NAME[0]}"
+          echo "::set-env name=AVD_WIDTH_PX::${DENSITY_VARIABLE_NAME[1]}"
+          echo "::set-env name=AVD_HEIGHT_PX::${DENSITY_VARIABLE_NAME[2]}"
 
       - name: Debug AVD variables
         run: echo "Debug avd name $AVD_NAME"; echo "Debug avd density $AVD_DENSITY"; echo "Debug avd width $AVD_WIDTH_PX"; echo "Debug avd height $AVD_HEIGHT_PX"
